-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.128.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 13/08/2016 11:26:32
-- Server version: 5.6.31
-- Client version: 4.1

USE validaciones;

DELIMITER $$

DROP PROCEDURE IF EXISTS Delete_tablas$$
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Delete_tablas()
BEGIN
delete from datosusutext;
  delete from  datosusuerrores;
END
$$

DROP PROCEDURE IF EXISTS Estado_Archivo$$
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Estado_Archivo()
BEGIN
SELECT * FROM  (SELECT COUNT(e.td_t) AS 'Numero de Registros' FROM datosusutext e ) AS r INNER JOIN (select COUNT(d.error_) AS 'Registros Erroneos' FROM  datosusuerrores d)  AS nnn ;
  

END
$$

DELIMITER ;